apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chaosmonkeys.io.github.lauripiispanen
spec:
  group: io.github.lauripiispanen
  names:
    kind: ChaosMonkey
    listKind: ChaosMonkeyList
    plural: chaosmonkeys
    singular: chaosmonkey
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ChaosMonkey is the Schema for the chaosmonkeys API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ChaosMonkeySpec defines the desired state of ChaosMonkey
          properties:
            interval:
              description: Pod killing interval in seconds
              format: int64
              type: integer
          required:
          - interval
          type: object
        status:
          description: ChaosMonkeyStatus defines the observed state of ChaosMonkey
          properties:
            lastruntime:
              format: int64
              type: integer
          required:
          - lastruntime
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
